baseURL = "https://lukeguillory.github.io/"
languageCode = "en-us"
title = "Hugo Grayscale Theme"
theme = "grayscale"
#googleAnalytics = ""
[params]
    # Provide some metadata for search and indexing services
    description = "A port of the Grayscale theme to Hugo"
    author = "RunningStream"
